### PR TITLE
fix: remove invalid exn handling

### PR DESCRIPTION
**Pull request by stijnmoreels**
Remove the attempt to log on unobserved exceptions.
We tried to retrieve back the registered logging system, but this is not only wrong, it is rather unstable.

We can either remove this, like in this PR, so that the consumers can see directly what's wrong with their scheduled job (authentication, processing failures...)
Or we can come up with a more resilient scheduled job that logs critical errors for unhandled exceptions in the scheduled job instead on relying on the incomplete 'unobsered exception handling'.

See also https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47 and https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48

### CODE REVIEW

**Comment by fgheysels** [comment]
So, what exactly happens now with removing this code ?   The background-job crashes on unhandled exceptions ?

**Comment by stijnmoreels** [comment]
> So, what exactly happens now with removing this code ? The background-job crashes on unhandled exceptions ?

Well, internally, the CronScheduler uses .NET hosted services, so the service will throw an exception, that's correct. The problem, really, is that we could have an handling logic in our background job, but we do not have access to the service provider or the dependency system. I created an issue here https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47 and provided a solution here https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48 but until now, there's no one responding 😢 .

**Comment by fgheysels** [comment]
> > So, what exactly happens now with removing this code ? The background-job crashes on unhandled exceptions ?
> 
> Well, internally, the CronScheduler uses .NET hosted services, so the service will throw an exception, that's correct. The problem, really, is that we could have an handling logic in our background job, but we do not have access to the service provider or the dependency system. I created an issue here [kdcllc/CronScheduler.AspNetCore#47](https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47) and provided a solution here [kdcllc/CronScheduler.AspNetCore#48](https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48) but until now, there's no one responding 😢 .

Looks like the repo isn't getting that much of attention/commits anyway ...
When the hosted service throws an exception that is not handled, isn't that service going to stop exectuing without further notice ?

**Comment by stijnmoreels** [comment]
> > > So, what exactly happens now with removing this code ? The background-job crashes on unhandled exceptions ?
> > 
> > 
> > Well, internally, the CronScheduler uses .NET hosted services, so the service will throw an exception, that's correct. The problem, really, is that we could have an handling logic in our background job, but we do not have access to the service provider or the dependency system. I created an issue here [kdcllc/CronScheduler.AspNetCore#47](https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47) and provided a solution here [kdcllc/CronScheduler.AspNetCore#48](https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48) but until now, there's no one responding 😢 .
> 
> Looks like the repo isn't getting that much of attention/commits anyway ... When the hosted service throws an exception that is not handled, isn't that service going to stop exectuing without further notice ?

Yeah, and I was just looking at their code, seems that in that case the exception is also not logged. Hmm, maybe we should implement our own exception handling strategy and let all our background jobs inherit from that.

**Comment by stijnmoreels** [comment]
Added some exception handling in the jobs themselves.

**Comment by fgheysels** [comment]
> handling strategy and let all our backg

That might be a good idea.

**Comment by stijnmoreels** [comment]
> > handling strategy and let all our backg
> 
> That might be a good idea.

Already done this in the changes, feel free to take a look. 👍

**Review by fgheysels — APPROVED** [review]
Great.

**Comment by kdcllc** [comment]
> > So, what exactly happens now with removing this code ? The background-job crashes on unhandled exceptions ?
> 
> Well, internally, the CronScheduler uses .NET hosted services, so the service will throw an exception, that's correct. The problem, really, is that we could have an handling logic in our background job, but we do not have access to the service provider or the dependency system. I created an issue here [kdcllc/CronScheduler.AspNetCore#47](https://github.com/kdcllc/CronScheduler.AspNetCore/issues/47) and provided a solution here [kdcllc/CronScheduler.AspNetCore#48](https://github.com/kdcllc/CronScheduler.AspNetCore/pull/48) but until now, there's no one responding 😢 .

I am sorry for the delay in including your functionality. I released the latest code todayhttps://github.com/kdcllc/CronScheduler.AspNetCore/pull/50. I hope this helps

**Pull request merged**
